### PR TITLE
ENH:  multi-metric for antsRegistrationSyN

### PR DESCRIPTION
**Pull request by ntustison**

### CODE REVIEW

**Comment by ntustison** [comment]
Hey @stnava , I can't reproduce these failures on my machine nor can I figure out what's going on.  It would seem there's an issue with the AdaptiveDenoising Module and the associated enumerated types defined there.  Have you had issues with compilation recently?

**Comment by stnava** [comment]
hi @ntustison 

I have not seen these errors either - I can probably try to look further over the Labor Day weekend .... 

may need an ITK version update ( ie update ITKR tag ) ...  when making changes that involve C++ ... just a guess.

**Comment by ntustison** [comment]
Awesome.  Thanks.  The changes I made were internal to ``antsRegistration.R`` so no C++ changes but who knows.  Thanks again.

**Comment by ntustison** [comment]
One potentially relevant difference between my local build and the GitHub checks is the ITKR versions:

* Local build:  ITKR_0.6.0.0.2 from stnava/ITKR
* GitHub check:  `` ITKR           0.5.3.3    2022-09-02 [1] Github (adigherman/ITKR@186128b)``

**Comment by ntustison** [comment]
Okay, updating to ITK_RC04 seems to have fixed the issue.  Now the problem seems to be with the checks that were there in the previous commit.  I'm going to go ahead and merge since it fixes the compilation and worry about the checks later.

**Pull request merged**
