### PR TITLE
ADD: extend image metrics

### PR DESCRIPTION
**Pull request by jeffduda**
Add ability to set nBins and radius for relevant metrics, set fixed and moving transforms (via 'antsrTransform') and get metric derivative. Example below illustrates a naming convention difference between this and the approach I took with 'antsrTransform'. They should probably be made consistent. I prefer the more recent 'class.method' naming, especially for thing that are mostly under the hood (i.e. not for noobs and casuls), but I'm open to ideas, thoughts? One advantage to the 'class.method' approach is tab completion showing all options for the class being used.

x =  antsImageRead( getANTsRData( 'r16' ))
y =  antsImageRead( getANTsRData( 'r30' ))
metric = antsrImageToImageMetric.Create(x,y,type="MeanSquares")
tx <- createAntsrTransform( precision="double", type="AffineTransform", dimension=2)
setAntsrTransformParameters(tx, c(0,-1,1,0,0,0))
setAntsrTransformFixedParameters(tx, c(128,128))
antsrImageToImageMetric.SetMovingTransform(metric, tx)
metricDeriv = antsrImageToImageMetric.GetDerivative(metric)

### CODE REVIEW

**Comment by muschellij2** [comment]
I think the "." is fine, but in roxygen2 that is usually reserved for when you want to make a generic function with a specific class associated to it so it'd be `antsrImageToImageMetric.antsImage` and similar `antsrImageToImageMetric.antsMatrix`

**Comment by jeffduda** [comment]
what about 'class_method' ? avoid the roxygen2 issue but still has the tab completion benefit.

**Comment by muschellij2** [comment]
That should work fine.  The period is still fine, but I'd recommend that
usage for creating S3 generics.  These are relatively long names for
functions though, so I may think about making them shorter or having a
wrapper.

John

**Comment by jeffduda** [comment]
maybe change the class to antsrMetric? That would cut the names way down but still gets the point across I think.

**Comment by stnava** [comment]
is this ready to be merged?

**Comment by muschellij2** [comment]
Please update the version before merging.

**Pull request merged**
